# Generated by Django 4.0.4 on 2022-12-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b_users',
            name='address',
        ),
        migrations.AddField(
            model_name='b_users',
            name='Btc_address',
            field=models.CharField(blank=True, max_length=38, null=True),
        ),
        migrations.AddField(
            model_name='b_users',
            name='private_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='b_users',
            name='public_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
