# Generated by Django 4.0.4 on 2022-12-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_b_users_address_b_users_btc_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400)),
            ],
        ),
    ]
